github:
  username: ${{ secrets.PAKETO_BUILDPACKS_DOCKERHUB_USERNAME }}
  token:    ${{ secrets.PAKETO_BOT_GITHUB_TOKEN }}

codeowners:
- path:  "*"
  owner: "@paketo-community/rust-maintainers"

package:
  repositories:   ["docker.io/paketocommunity/rustup"]
  register:       true
  registry_token: ${{ secrets.PAKETO_BOT_GITHUB_TOKEN }}

docker_credentials:
  - registry: docker.io
    username: ${{ secrets.PAKETO_BUILDPACKS_DOCKERHUB_USERNAME }}
    password: ${{ secrets.PAKETO_BUILDPACKS_DOCKERHUB_PASSWORD }}

dependencies:
- name: Rustup Init GNU
  id:   rustup-init-gnu
  uses: docker://ghcr.io/paketo-buildpacks/actions/rustup-init-dependency:main
  with:
    target: x86_64-unknown-linux-gnu
    token: ${{ secrets.PAKETO_BOT_GITHUB_TOKEN }}
- name: Rustup Init MUSL
  id:   rustup-init-musl
  uses: docker://ghcr.io/paketo-buildpacks/actions/rustup-init-dependency:main
  with:
    target: x86_64-unknown-linux-musl
    token: ${{ secrets.PAKETO_BOT_GITHUB_TOKEN }}

# ARM64
- name: Rustup Init GNU ARM64
  id:   rustup-init-gnu
  uses: docker://ghcr.io/paketo-buildpacks/actions/rustup-init-dependency:main
  with:
    target: aarch64-unknown-linux-gnu
    token: ${{ secrets.PAKETO_BOT_GITHUB_TOKEN }}
    arch: arm64
- name: Rustup Init MUSL ARM64
  id:   rustup-init-musl
  uses: docker://ghcr.io/paketo-buildpacks/actions/rustup-init-dependency:main
  with:
    target: aarch64-unknown-linux-musl
    token: ${{ secrets.PAKETO_BOT_GITHUB_TOKEN }}
    arch: arm64
