github:
  username: ${{ secrets.PAKETO_BUILDPACKS_DOCKERHUB_USERNAME }}
  token:    ${{ secrets.PAKETO_BOT_GITHUB_TOKEN }}

codeowners:
- path:  "*"
  owner: "@paketo-community/rust-maintainers"

package:
  repositories:   ["docker.io/paketocommunity/rustup","gcr.io/paketo-community/rustup"]
  register:       true
  registry_token: ${{ secrets.PAKETO_BOT_GITHUB_TOKEN }}

docker_credentials:
  - registry: gcr.io
    username: _json_key
    password: ${{ secrets.GCR_PUSH_BOT_JSON_KEY }}
  - registry: docker.io
    username: ${{ secrets.PAKETO_BUILDPACKS_DOCKERHUB_USERNAME }}
    password: ${{ secrets.PAKETO_BUILDPACKS_DOCKERHUB_PASSWORD }}

dependencies:
- id:   rustup-init-gnu
  uses: docker://ghcr.io/paketo-buildpacks/actions/rustup-init-dependency:main
  with:
    target: x86_64-unknown-linux-gnu
    token: ${{ secrets.PAKETO_BOT_GITHUB_TOKEN }}
- id:   rustup-init-musl
  uses: docker://ghcr.io/paketo-buildpacks/actions/rustup-init-dependency:main
  with:
    target: x86_64-unknown-linux-musl
    token: ${{ secrets.PAKETO_BOT_GITHUB_TOKEN }}
