# Copyright 2018-2021 the original author or authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

api = "0.6"

[buildpack]
id       = "paketo-community/rustup"
name     = "Paketo Rustup Buildpack"
version  = "{{.version}}"
homepage = "https://github.com/paketo-community/rustup"
description = "A Cloud Native Buildpack that installs and executes `rustup` to install Rust"
keywords    = ["rust", "rustup"]

[[buildpack.licenses]]
type = "Apache-2.0"
uri  = "https://github.com/paketo-community/rustup/blob/main/LICENSE"

[[stacks]]
id = "io.buildpacks.stacks.bionic"

[[stacks]]
id = "io.paketo.stacks.tiny"

[[stacks]]
id = "*"

[[metadata.dependencies]]
id      = "rustup-gnu"
name    = "Rustup (GNU libc)"
version = "1.24.3"
uri     = "https://static.rust-lang.org/rustup/dist/x86_64-unknown-linux-gnu/rustup-init"
sha256  = "3dc5ef50861ee18657f9db2eeb7392f9c2a6c95c90ab41e45ab4ca71476b4338"
stacks  = [ "io.buildpacks.stacks.bionic", "io.paketo.stacks.tiny", "*" ]

  [[metadata.dependencies.licenses]]
  type = "Apache-2.0"
  uri  = "https://github.com/rust-lang/rustup/blob/master/LICENSE-APACHE"

  [[metadata.dependencies.licenses]]
  type = "MIT"
  uri  = "https://github.com/rust-lang/rustup/blob/master/LICENSE-MIT"

[[metadata.dependencies]]
id      = "rustup-musl"
name    = "Rustup (musl libc)"
version = "1.24.3"
uri     = "https://static.rust-lang.org/rustup/dist/x86_64-unknown-linux-gnu/rustup-init"
sha256  = "3dc5ef50861ee18657f9db2eeb7392f9c2a6c95c90ab41e45ab4ca71476b4338"
stacks  = [ "io.buildpacks.stacks.bionic", "io.paketo.stacks.tiny", "*" ]

  [[metadata.dependencies.licenses]]
  type = "Apache-2.0"
  uri  = "https://github.com/rust-lang/rustup/blob/master/LICENSE-APACHE"

  [[metadata.dependencies.licenses]]
  type = "MIT"
  uri  = "https://github.com/rust-lang/rustup/blob/master/LICENSE-MIT"

[metadata]
pre-package   = "scripts/build.sh"
include-files = [
  "LICENSE",
  "NOTICE",
  "README.md",
  "bin/build",
  "bin/detect",
  "bin/main",
  "buildpack.toml",
]
