# Copyright 2018-2024 the original author or authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

api = "0.7"

[buildpack]
  description = "A Cloud Native Buildpack that installs and executes `rustup` to install Rust"
  homepage = "https://github.com/paketo-community/rustup"
  id = "paketo-community/rustup"
  keywords = ["rust", "rustup"]
  name = "Paketo Buildpack for Rustup"
  sbom-formats = ["application/vnd.cyclonedx+json", "application/vnd.syft+json"]
  version = "{{.version}}"

  [[buildpack.licenses]]
    type = "Apache-2.0"
    uri = "https://github.com/paketo-community/rustup/blob/main/LICENSE"

[metadata]
  include-files = ["LICENSE", "NOTICE", "README.md", "buildpack.toml", "linux/amd64/bin/build", "linux/amd64/bin/detect", "linux/amd64/bin/main", "linux/arm64/bin/build", "linux/arm64/bin/detect", "linux/arm64/bin/main"]
  pre-package = "scripts/build.sh"

  [[metadata.configurations]]
    build = true
    default = "stable"
    description = "the Rust toolchain or version number to install"
    name = "BP_RUST_TOOLCHAIN"

  [[metadata.configurations]]
    build = true
    default = "minimal"
    description = "the Rust profile to install"
    name = "BP_RUST_PROFILE"

  [[metadata.configurations]]
    build = true
    default = ""
    description = "an additional Rust target to install"
    name = "BP_RUST_TARGET"

  [[metadata.configurations]]
    build = true
    default = "true"
    description = "use rustup to install Rust"
    name = "BP_RUSTUP_ENABLED"

  [[metadata.configurations]]
    build = true
    default = "1"
    description = "the rustup version"
    name = "BP_RUSTUP_INIT_VERSION"

  [[metadata.configurations]]
    build = true
    default = "gnu"
    description = "libc implementation: gnu or musl"
    name = "BP_RUSTUP_INIT_LIBC"

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:rust:rustup:1.27.1:*:*:*:*:*:*:*"]
    id = "rustup-init-gnu"
    name = "Rustup (GNU libc)"
    purl = "pkg:generic/rustup@1.27.1?arch=amd64"
    sha256 = "6aeece6993e902708983b209d04c0d1dbb14ebb405ddb87def578d41f920f56d"
    source = "https://github.com/rust-lang/rustup/archive/refs/tags/1.27.1.tar.gz"
    source-sha256 = "f5ba37f2ba68efec101198dca1585e6e7dd7640ca9c526441b729a79062d3b77"
    stacks = ["*"]
    uri = "https://static.rust-lang.org/rustup/archive/1.27.1/x86_64-unknown-linux-gnu/rustup-init"
    version = "1.27.1"

    [[metadata.dependencies.licenses]]
      type = "Apache-2.0"
      uri = "https://github.com/rust-lang/rustup/blob/master/LICENSE-APACHE"

    [[metadata.dependencies.licenses]]
      type = "MIT"
      uri = "https://github.com/rust-lang/rustup/blob/master/LICENSE-MIT"

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:rust:rustup:1.27.0:*:*:*:*:*:*:*"]
    id = "rustup-init-musl"
    name = "Rustup (musl libc)"
    purl = "pkg:generic/rustup@1.27.0?arch=amd64"
    sha256 = "b9d84cbba1ed29d11c534406a1839d64274d29805041e0e096d5293ae6390dd0"
    source = "https://github.com/rust-lang/rustup/archive/refs/tags/1.27.0.tar.gz"
    source-sha256 = "3d331ab97d75b03a1cc2b36b2f26cd0a16d681b79677512603f2262991950ad1"
    stacks = ["*"]
    uri = "https://static.rust-lang.org/rustup/archive/1.27.0/x86_64-unknown-linux-musl/rustup-init"
    version = "1.27.0"

    [[metadata.dependencies.licenses]]
      type = "Apache-2.0"
      uri = "https://github.com/rust-lang/rustup/blob/master/LICENSE-APACHE"

    [[metadata.dependencies.licenses]]
      type = "MIT"
      uri = "https://github.com/rust-lang/rustup/blob/master/LICENSE-MIT"

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:rust:rustup:1.27.0:*:*:*:*:*:*:*"]
    id = "rustup-init-gnu"
    name = "Rustup (GNU libc)"
    purl = "pkg:generic/rustup@1.27.0?arch=arm64"
    sha256 = "76cd420cb8a82e540025c5f97bda3c65ceb0b0661d5843e6ef177479813b0367"
    source = "https://github.com/rust-lang/rustup/archive/refs/tags/1.27.0.tar.gz"
    source-sha256 = "3d331ab97d75b03a1cc2b36b2f26cd0a16d681b79677512603f2262991950ad1"
    stacks = ["*"]
    uri = "https://static.rust-lang.org/rustup/archive/1.27.0/aarch64-unknown-linux-gnu/rustup-init"
    version = "1.27.0"

    [[metadata.dependencies.licenses]]
      type = "Apache-2.0"
      uri = "https://github.com/rust-lang/rustup/blob/master/LICENSE-APACHE"

    [[metadata.dependencies.licenses]]
      type = "MIT"
      uri = "https://github.com/rust-lang/rustup/blob/master/LICENSE-MIT"

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:rust:rustup:1.27.0:*:*:*:*:*:*:*"]
    id = "rustup-init-musl"
    name = "Rustup (musl libc)"
    purl = "pkg:generic/rustup@1.27.0?arch=arm64"
    sha256 = "841513f7599fcf89c71a62dea332337dfd4332216b60c17648d6effbeefe66a9"
    source = "https://github.com/rust-lang/rustup/archive/refs/tags/1.27.0.tar.gz"
    source-sha256 = "3d331ab97d75b03a1cc2b36b2f26cd0a16d681b79677512603f2262991950ad1"
    stacks = ["*"]
    uri = "https://static.rust-lang.org/rustup/archive/1.27.0/aarch64-unknown-linux-musl/rustup-init"
    version = "1.27.0"

    [[metadata.dependencies.licenses]]
      type = "Apache-2.0"
      uri = "https://github.com/rust-lang/rustup/blob/master/LICENSE-APACHE"

    [[metadata.dependencies.licenses]]
      type = "MIT"
      uri = "https://github.com/rust-lang/rustup/blob/master/LICENSE-MIT"

[[stacks]]
  id = "*"

[[targets]]
  arch = "amd64"
  os = "linux"

[[targets]]
  arch = "arm64"
  os = "linux"
